ArticleCreateFail = "Article Create Fail"
ArticleCreateSuccessMsg = "Article {{.title}} created successfully."
ArticleCreateSuccessTitle = "Article Create Successful"
ArticleCreateTitleExistMsg = "An article with same title already exists. Please specify another title."
MeLoginInvalidMsg = "Invalid username and/or password."
MeLoginInvalidTitle = "Login Fail"
MeLoginSuccessMsg = "Welcome {{.username}}!"
MeLoginSuccessTitle = "Login Successful"
TenantCreateFail = "Tenant Create Fail"
TenantCreateNameExistsMsg = "A tenant with same name already exists. Please specify another name."
TenantCreateSuccessMsg = "Tenant {{.name}} created successfully."
TenantCreateSuccessTitle = "Tenant Create Successful"
UserCreateFailTitle = "User Create Fail"
UserCreateSuccessMsg = "User {{.username}} created successfully."
UserCreateSuccessTitle = "User Create Successful"
UserCreateUsernameExistsMsg = "A user with same username already exists. Please specify another username."
